services:
  mysql:
    image: mysql:8.3
    container_name: blogdemensajes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_blog_mensajes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=caching_sha2_password"]
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: blogdemensajes-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
