services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_APPOINTMENTS_USER_PASSWORD: ${MYSQL_APPOINTMENTS_USER_PASSWORD}
      MYSQL_SELECT_USER_PASSWORD: ${MYSQL_SELECT_USER_PASSWORD}
      MYSQL_UPDATE_PASSWORD: ${MYSQL_UPDATE_PASSWORD}
      MYSQL_UPDATE_SCHEMA_PASSWORD: ${MYSQL_UPDATE_SCHEMA_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: 
    #Usa el plugin mysql_native_password para compatibilidad con clientes antiguos (evita problemas con caching_sha2_password)
    - --default-authentication-plugin=mysql_native_password
    #Permite crear funciones seguras cuando el binlog est√° activado sin necesitar privilegios SUPER
    - --log-bin-trust-function-creators=1

volumes:
  mysql_data:
